package(default_visibility = ["//visibility:public"])

load("@npm_bazel_typescript//:defs.bzl", "ts_library")

ts_library(
    name = "components",
    srcs = ["hello.tsx"],
    deps = [
        "@npm//@types/react",
    ],
)
