package(default_visibility = ["//visibility:public"])

load("@npm_bazel_typescript//:index.bzl", "ts_library")

ts_library(
    name = "sidebar",
    srcs = ["index.tsx"],
    deps = [
        "@npm//@types/react",
    ],
)
